# staging 

FROM python:3.4 AS staging
ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt

# production

FROM staging AS prod

COPY --from=staging /code /prod_code

CMD ["python", "app.py"]
